global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.163.com:25'
  smtp_from: 'nanwanwang@163.com'
  smtp_auth_username: 'nanwanwang@163.com'
  smtp_auth_password: '7546319ily'
  smtp_hello: '163.com'
  smtp_require_tls: false
route:
  group_by: ['job', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: default
  routes:
  - receiver: webhook
    match:
      alertname: CoreDNSDown
receivers:
- name: 'default'
  email_configs:
  - to: '766066375@qq.com'
    send_resolved: true
# - name: 'webhook'
#   webhook_configs:
#   - url: 'http://dingtalk-hook.kube-ops:5000'
#     send_resolved: true