apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: kube-ops
data:
  grafana.ini: |
    [server]
    root_url = http://172.16.188.111:30336
    [smtp]
    enabled = true
    host = smtp.163.com:25
    user = nanwanwang@163.com
    password = 7546319ily
    skip_verify = true
    from_address = nanwanwang@163.com
    [alerting]
    enabled = true
    execute_alerts = true

